apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: psql-dev
spec:
  ports:
    - port: 5432 # Порт по умолчанию для PostgreSQL
  clusterIP: None # Обязательно для StatefulSet, чтобы обеспечить DNS для каждого пода
  selector:
    app: postgres
