apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark
  namespace: spark-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
  template:
    metadata:
      labels:
        app: spark
    spec:
      containers:
        - name: spark
          image: spark-jupyter:3.5.8
          # image: alexmerced/spark35nb:latest
          # image: spark-hadoop:3.5.1
          # imagePullPolicy: IfNotPresent
          imagePullPolicy: Never
          command: ["jupyter"]
          args:
            - lab
            - "--ip=0.0.0.0"
            - "--no-browser"
            - "--allow-root"
            - "--NotebookApp.token=''"
            - "--NotebookApp.password=''"          
          ports:
            - containerPort: 8080  # Spark Master UI
            - containerPort: 7077  # Spark Master Port
            - containerPort: 4040  # Spark App Port
            - containerPort: 8888  # Jupyter Notebook
          volumeMounts:
            - name: spark-storage
              mountPath: /workspace   # Jupyter default notebook directory            
          env:
            - name: AWS_ACCESS_KEY_ID
              value: "minio"
            - name: AWS_SECRET_ACCESS_KEY
              value: "minio123"
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
            - name: AWS_REGION
              value: "us-east-1"
      volumes:
        - name: spark-storage
          persistentVolumeClaim:
            claimName: data-spark
            
